#    _____            _     _____        _      #
#   |  __ \          | |   |  __ \      | |     #
#   | |  | | __ _ ___| |__ | |  | | ___ | |_    #
#   | |  | |/ _` / __| '_ \| |  | |/ _ \| __|   #
#   | |__| | (_| \__ \ | | | |__| | (_) | |_    #
#   |_____/ \__,_|___/_| |_|_____/ \___/ \__|   #
#                                               #                                       

version: '3.5'
services:  
  dash:    
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped     
    privileged: true # Required for CPU temperature monitoring  
    ports:      
      - '8338:3001' # Web UI port
    volumes:    
      - /:/mnt/host:ro # Mount the host root filesystem as read-only   
    environment:      
      - DASHDOT_SHOW_HOST= 'true' # Show hostname     
      - DASHDOT_SHOW_DASH_VERSION= 'true' # Show dash version     
      - DASHDOT_ENABLE_CPU_TEMPS= 'true' # Enable CPU temperature monitoring     
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES= 'true' # Always show percentages