#    _____            _     _____        _      #
#   |  __ \          | |   |  __ \      | |     #
#   | |  | | __ _ ___| |__ | |  | | ___ | |_    #
#   | |  | |/ _` / __| '_ \| |  | |/ _ \| __|   #
#   | |__| | (_| \__ \ | | | |__| | (_) | |_    #
#   |_____/ \__,_|___/_| |_|_____/ \___/ \__|   #
#                                               #                                       

version: '3.5'
services:  
  dash:    
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped    
    privileged: true    
    ports:      
      - '8338:3001'    
    volumes:    
      - /:/mnt/host:ro   
    environment:      
      - DASHDOT_SHOW_HOST= 'true'      
      - DASHDOT_SHOW_DASH_VERSION= 'true'      
      - DASHDOT_ENABLE_CPU_TEMPS= 'true'      
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES= 'true'